<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Specialty extends Model
{
    /** @use HasFactory<\Database\Factories\SpecialtyFactory> */
    use HasFactory;

    public static array $specialties = [
        'Software Engineering',
        'Data Science',
        'Artificial Intelligence',
        'Cybersecurity',
        'Computer Networks',
        'Web Development',
        'Mobile App Development',
        'Game Development',
        'Computer Graphics',
        'Human-Computer Interaction',
        'Machine Learning',
        'Cloud Computing',
        'DevOps Engineering',
        'Information Systems',
        'Database Management',
        'Biotechnology',
        'Bioinformatics',
        'Molecular Biology',
        'Cell Biology',
        'Genetics',
        'Microbiology',
        'Immunology',
        'Neuroscience',
        'Biochemistry',
        'Environmental Biotechnology',
        'Pharmaceutical Sciences',
        'Pharmacology',
        'Toxicology',
        'Clinical Research',
        'Medical Laboratory Science',
        'Radiology',
        'Cardiology',
        'Neurology',
        'Pediatrics',
        'Gynecology',
        'Orthopedics',
        'Dermatology',
        'Ophthalmology',
        'Psychiatry',
        'Anesthesiology',
        'Emergency Medicine',
        'Family Medicine',
        'Internal Medicine',
        'Surgery',
        'Public Health',
        'Epidemiology',
        'Health Administration',
        'Nursing Practice',
        'Midwifery',
        'Physical Therapy',
        'Occupational Therapy',
        'Speech Therapy',
        'Nutrition and Dietetics',
        'Sports Medicine',
        'Rehabilitation Sciences',
        'Civil Engineering',
        'Structural Engineering',
        'Geotechnical Engineering',
        'Transportation Engineering',
        'Environmental Engineering',
        'Water Resources Engineering',
        'Urban Planning',
        'Landscape Architecture',
        'Construction Management',
        'Mechanical Engineering',
        'Thermodynamics',
        'Fluid Mechanics',
        'Mechatronics',
        'Robotics Engineering',
        'Automotive Engineering',
        'Aerospace Engineering',
        'Aviation Management',
        'Electrical Engineering',
        'Electronics Engineering',
        'Power Engineering',
        'Renewable Energy Systems',
        'Telecommunications',
        'Signal Processing',
        'Embedded Systems',
        'Microelectronics',
        'Photonics',
        'Chemical Engineering',
        'Process Engineering',
        'Petroleum Engineering',
        'Polymer Science',
        'Materials Engineering',
        'Nanotechnology',
        'Metallurgy',
        'Ceramics Engineering',
        'Industrial Engineering',
        'Operations Research',
        'Supply Chain Management',
        'Logistics',
        'Quality Management',
        'Manufacturing Engineering',
        'Textile Engineering',
        'Agricultural Engineering',
        'Food Science',
        'Food Technology',
        'Veterinary Science',
        'Animal Science',
        'Plant Science',
        'Soil Science',
        'Agronomy',
        'Horticulture',
        'Forestry',
        'Wildlife Biology',
        'Marine Biology',
        'Oceanography',
        'Environmental Science',
        'Climate Science',
        'Meteorology',
        'Geology',
        'Geophysics',
        'Mining Engineering',
        'Surveying',
        'Cartography',
        'Astronomy',
        'Astrophysics',
        'Physics',
        'Quantum Physics',
        'Nuclear Physics',
        'Particle Physics',
        'Condensed Matter Physics',
        'Theoretical Physics',
        'Chemistry',
        'Organic Chemistry',
        'Inorganic Chemistry',
        'Physical Chemistry',
        'Analytical Chemistry',
        'Industrial Chemistry',
        'Mathematics',
        'Applied Mathematics',
        'Pure Mathematics',
        'Statistics',
        'Actuarial Science',
        'Financial Mathematics',
        'Economics',
        'Econometrics',
        'Finance',
        'Investment Management',
        'Risk Management',
        'Banking',
        'Accounting',
        'Auditing',
        'Taxation',
        'Business Administration',
        'International Business',
        'Entrepreneurship',
        'Marketing',
        'Digital Marketing',
        'Brand Management',
        'Advertising',
        'Public Relations',
        'Media Studies',
        'Journalism',
        'Broadcasting',
        'Film Production',
        'Digital Media',
        'Graphic Design',
        'Industrial Design',
        'Fashion Design',
        'Textile Design',
        'Interior Design',
        'Game Art',
        'Animation',
        'VFX',
        'Photography',
        'Visual Arts',
        'Fine Arts',
        'Sculpture',
        'Painting',
        'Music',
        'Music Production',
        'Music Education',
        'Theater Arts',
        'Performing Arts',
        'Dance',
        'Choreography',
        'Literature',
        'Creative Writing',
        'Poetry',
        'Playwriting',
        'Screenwriting',
        'Linguistics',
        'Applied Linguistics',
        'Translation Studies',
        'Interpreting',
        'Modern Languages',
        'Classical Languages',
        'Latin Studies',
        'Ancient Greek Studies',
        'History',
        'Ancient History',
        'Medieval History',
        'Modern History',
        'Art History',
        'Architecture',
        'Architectural Engineering',
        'Heritage Conservation',
        'Museology',
        'Archival Studies',
        'Library Science',
        'Information Management',
        'Philosophy',
        'Ethics',
        'Logic',
        'Epistemology',
        'Metaphysics',
        'Political Science',
        'International Relations',
        'Diplomacy',
        'Comparative Politics',
        'Public Policy',
        'Public Administration',
        'Governance',
        'Sociology',
        'Anthropology',
        'Cultural Studies',
        'Gender Studies',
        'Ethnic Studies',
        'Religious Studies',
        'Theology',
        'Divinity',
        'Psychology',
        'Clinical Psychology',
        'Counseling Psychology',
        'Educational Psychology',
        'Child Development',
        'Forensic Psychology',
        'Social Work',
        'Community Development',
        'Criminology',
        'Criminal Justice',
        'Law',
        'Corporate Law',
        'Criminal Law',
        'International Law',
        'Environmental Law',
        'Human Rights Law',
        'Family Law',
        'Education',
        'Early Childhood Education',
        'Primary Education',
        'Secondary Education',
        'Special Education',
        'Higher Education',
        'Adult Education',
        'Curriculum Development',
        'Educational Leadership',
        'Physical Education',
        'Sport Science',
        'Kinesiology',
        'Exercise Physiology',
        'Coaching',
        'Athletic Training',
        'Recreation Management',
        'Tourism Management',
        'Hospitality Management',
        'Event Management',
        'Culinary Arts',
        'Pastry Arts',
        'Hotel Management',
        'Aviation Management',
        'Maritime Studies',
        'Nautical Science',
        'Logistics Management',
        'Supply Chain Management',
        'Transportation Management',
        'Urban Studies',
        'Regional Planning',
        'Geography',
        'Human Geography',
        'Physical Geography',
        'Geographic Information Systems (GIS)',
        'Remote Sensing',
    ];
    public function institution(): BelongsTo
    {
        return $this->belongsTo(Institution::class);
    }
}
